name: MultiFeatureCore
version: '2.1.0'
main: com.jokholk.multifeature.MainPlugin
api-version: '1.21.7'
load: STARTUP

authors: [Jok Holk]
description: A multi-feature core plugin providing personal fast travel, customizable ranks, chat prefix, nametag, and toggleable scoreboard.
website: https://jokholk.dev

commands:
  travel:
    description: Fast travel system
    usage: /travel [save|load|name|delete]

  rank:
    description: Manage player ranks
    usage: /rank <player> <rank>

  scoreboard:
    description: Toggle scoreboard
    usage: scoreboard [on|off]

permissions:

  multifeature.travel:
    description: Access fast travel system
    default: true

  multifeature.admin:
    description: Manage ranks
    default: op

  multifeature.checkpoint.save:
    description: Save checkpoints
    default: true

  multifeature.checkpoint.load:
    description: Load checkpoints
    default: true

  multifeature.checkpoint.rename:
    description: Rename checkpoints
    default: true
